### PR TITLE
Add grouping tags.

### PR DESCRIPTION
**Pull request by lakshmivyas**
- Add book, chapter and section tags along with LOs
- Add expectations to the spec to ensure that those
  tags are present

\cc @Dantemss, @jpslav

### CODE REVIEW

**Comment by Dantemss** [comment]
Seems good for now, but if the section is needed, in the future I might ask Greg to explicitly add back in the section tag column (he has it already in his master spreadsheet I believe)

**Comment by lakshmivyas** [comment]
@Dantemss - yeah that's a good idea.  We definitely need more structure to our tags.

**Comment by philschatz** [comment]
Hmm, is the hierarchy needed for BigLearn or could tutor just filter out the chapter/section tags (or TF/IDF them)?

The goal of the original naming was mostly just to avoid collisions with other tags; things like the location of dashes, whether the number is 0-padded, and the choice of characters preceding the number (like `-ch#`, `-s#`, or `-lo#`) were somewhat arbitrarily decided.

**Comment by lakshmivyas** [comment]
@philschatz - maybe we should all huddle up and talk about this some more. \cc @kevinburleigh75

**Pull request merged**
