### PR TITLE
Books breakdown

### PR DESCRIPTION
**Pull request by Dantemss**
For: https://github.com/openstax/unified/issues/2156

### CODE REVIEW

**Comment by Dantemss** [comment]
I... think this is ready but I forgot to mark as ready and ask for reviews for some reason

**Comment by Dantemss** [comment]
The card that required this has already been completed, so this is low-priority, just in case we need to run this again.

**Review by jivey — COMMENTED** [review]
Is prod:read-only enough to pull exercises? I get `0`s for all the exercise counts, but maybe it's a permissions thing.

**Comment by Dantemss** [comment]
The role shouldn't matter as long as it gives you access to the server...
If you are testing locally, you might just not have any A&P exercises locally.

**Comment by jivey** [comment]
Yeah, skimmed it and forgot that is an AR model and not a client ☕ ⬇️

**Review by jivey — APPROVED** [review]

**Pull request merged**
