### PR TITLE
Lock down solutions

### PR DESCRIPTION
**Pull request by Dantemss**
- Fix up Doorkeeper controller so apps can be added once more
- Solutions, correctness and feedback can now only be viewed by Exercise authors, copyright holders, editors and apps added by admins
- Added a rake task to create a Tutor app in Exercises during deployment

### CODE REVIEW

**Comment by jpslav** [comment]
Like the direction

**Comment by Dantemss** [comment]
This PR is done. The rest has to happen in tutor-deployment.

**Comment by jpslav** [comment]
Looks good. 

1. Do we need to wait for changes to tutor-deployment before merging? (if we don't wait will we break -dev?)
2. I believe we will need changes to tutor-server to serve exercises to the FE for reference view and the HW builder.  Do you agree? (think FE is hitting Exercises directly now for these)
3. @kevinburleigh75 does BigLearn hit Exercises directly and does this locking down affect it?

**Comment by Dantemss** [comment]
1, Hopefully merge both PR's at the same time (the PR's reference each other in the comments).
2. I think they get HW exercises from the BE, so I guess you are right, we would have to provide an endpoint for the reference view exercises (if we need feedback/solutions there).

**Pull request merged**
